ontohub/ontohub

config/god/app.rb, config/settings.yml
This shall fix #1150.
Now the number of hets workers can be configured by the admin, but it is restricted to
* at least one
* at most "number of processors" minus "number of other high load workers" (2)
=> Add setting for hets workers count.

app/assets/javascripts/files.js.coffee, app/controllers/filetypes_controller.rb, app/models/file_extension_mime_type_mapping.rb, app/models/repository_file.rb, app/views/files/new.html.haml, config/database_cleaner.rb, config/hets.yml, config/routes.rb, db/migrate/20141206161905_create_file_extension_mime_type_mappings.rb, db/migrate/20141206163145_add_mappings_to_file_extension_mime_type_mappings.rb, db/seeds.rb, lib/file_retriever.rb, lib/hets.rb, lib/hets/caller.rb, lib/hets/errors.rb, lib/hets/filetype_caller.rb, lib/hets/version_caller.rb, lib/uri_fetcher.rb, spec/controllers/filetypes_controller_spec.rb
Should fix #28. Needs the current version of hets.
=> 28 remote file upload

app/assets/images/icons/single_ontology.svg, app/assets/stylesheets/data_type.css.sass, app/views/files/_show_dir.html.haml, app/views/home/_versions.html.haml, app/views/logics/_distributed.html.haml, app/views/logics/_heterogeneous_distributed.html.haml, app/views/logics/_ontologies.html.haml
Should basically be as advertised: Improves spacing for ontology-fancy-link (the svg-icons) in specific lists. This should remove the overlap between multiple heterogeneous-ontology icons.
=> Improve ontology list display

app/models/commit.rb, app/models/history_entries_page.rb, app/models/ontology_version.rb, app/models/repository.rb, app/models/repository/git_repositories.rb, db/migrate/20150128133702_create_commits.rb, db/migrate/20150128141231_add_commit_reference_to_ontology_version.rb, lib/hets/node_evaluation_helper.rb, lib/tasks/migrate_data.rake, spec/lib/repository/import/svn_spec.rb, spec/models/commit_spec.rb, spec/models/ontology_version_spec.rb, spec/models/repository_directory_spec.rb
Should fix #1171, which again should help with the completion of #1154.
=> 1171 add commit model

Gemfile, Gemfile.lock, app/controllers/ontologies_controller.rb, app/models/repository/destroying.rb, app/views/ontologies/_menu.html.haml, app/views/ontologies/index_repository.html.haml, app/views/ontologies/new.html.haml, config/settings.yml
added new gem and used its method 'with_indefinite_article' for all the found instances where it can be applied.
=> 1087 correct indefinite article for oms

spec/spec_helper.rb
This enables colorized rspec output in jenkins.
=> Colorize the output, if the environment says so.

app/assets/javascripts/repository/edit_remote.js.coffee, app/controllers/repositories_controller.rb, app/models/repository.rb, app/models/repository/importing.rb, app/views/repositories/_form.html.haml, config/locales/en.yml, config/locales/simple_form.en.yml, db/migrate/20140916084320_add_remote_type_to_repository.rb, spec/controllers/files_controller_spec.rb, spec/controllers/repositories_controller_spec.rb, spec/controllers/ssh_access_controller_spec.rb, spec/factories/repository_factory.rb, spec/lib/repository/import/git_spec.rb, spec/lib/repository/import/svn_spec.rb, spec/lib/sidetiq_worker_spec.rb, spec/lib/ssh_access_spec.rb, spec/models/repository/git_mv_spec.rb, spec/models/repository/git_spec.rb, spec/models/repository/remote_spec.rb
Shall fix both issues of #634 (and #351): Allowing to fork a repository and converting a mirror to a local repository.
This also improves the javascript in the new repository view as it now updates everytime the source address is changed (key press, click, cut, paste) and not only when its input field loses focus.
=> 634 fork and unmirror repository

config/god/hets_workers.rb, config/hets.yml, lib/hets/parse_caller.rb, lib/tasks/hets.rake, spec/fixtures/ontologies/dol/CompetencyQuestion.dol, spec/models/ontology_spec.rb
=> 1200 call hets with auto

config/god/app.rb
This shall fix #1151. God didn't start because it failed while reading the configuration.
First, the method `hets_workers_count` was not visible in the configure
block. Moving it up fixes this.
Second, the Rails environment is not available. Loading the yml file
manually fixes this.
=> Make god listen again

app/models/ontology.rb, app/models/ontology/symbols.rb, app/models/ontology_version.rb, db/migrate/20150217121518_create_loc_ids_for_existing_ontologies.rb, lib/hets.rb, spec/models/ontology_version_spec.rb
Shall fix #1211. Additionally provides the migration to update existing data with locids.
=> 1211 fix ref locids for subdirectories

app/assets/javascripts/ontology_version-state.js.coffee, features/OntologyState.feature, features/step_definitions/ontology_state_steps.rb, features/support/env.rb
=> 1218 ontology state feature test

script/stylecheck
This script runs rubocop with a suitable config generated from the
`.hound.yml`. The hound config includes a key that's not compatible with
rubocop. The config is copied to a tempfile without that key.
You can check your code for compliance with the style guide by running
```
script/stylecheck
```
in the ontohub directory. You can also specify a list of files and folders to go
through with
```
script/stylecheck app/models/ontology.rb app/models/ontology/
```
=> Add stylecheck script

app/controllers/filetypes_controller.rb, app/models/hets_instance.rb, lib/hets.rb, lib/hets/parse_caller.rb, spec/controllers/filetypes_controller_spec.rb, spec/models/hets_instance_spec.rb, spec/spec_helper.rb
Produce a little bit more readable and reasonable errors when there is no (useable) hets instance registered.
=> Add reasonable errors for hets instances

app/assets/javascripts/ontology_version-state.js.coffee
If the ontology state is not terminal (a final state), then we should
only re-enqueue the particular container instead of all (which would
lead to a lot more jobs being created).
=> re-enqueue only specific container if not terminal

Gemfile.lock, app/controllers/formality_levels_controller.rb, app/controllers/license_models_controller.rb, app/controllers/logics_controller.rb, app/controllers/mappings_controller.rb, app/controllers/ontologies_controller.rb, app/controllers/repositories_controller.rb, app/controllers/sentences_controller.rb, app/controllers/symbols_controller.rb, config/initializers/custom_mime_types.rb, config/routes.rb
I've reduced that to the API relevant controllers, as i'm not entirely sure what all controllers should actually respond to. So this will close #1166.
=> 1166 add mimetype info to controllers

app/models/repository/importing.rb, app/models/repository/validations.rb, lib/git_repository/cloning.rb
This fixes #1159 and a few other git/cloning related bugs (see first commits).
When a private git repository is supposed to be cloned, git usually asks for credentials. This prompt is prevented by asking `/bin/true` for them. Of course, `true` doesn't supply any, but exits with code `SUCCESS`, so git thinks they are supplied and fails because the credentials don't fit to the repository.
*I removed the previous workaround-commits by rebase (see original message).*
This is more of a workaround than a fix for #1159.
I don't see any fast way to check if something is a git repository than `git ls-remote`. However, this asks for credentials when calling it on a github private repository.
I tried to read the login prompt of `git ls-remote` in `Subprocess.run`, but I could not get my hands on the …
=> 1159 create mirror of private GitHub repository

app/assets/javascripts/ontology_version-state.js.coffee, app/helpers/ontology_helper.rb, features/step_definitions/ontology_state_steps.rb, features/support/env.rb, lib/ontology_version_finder.rb
Shall fix the ontology state feature yet again. This time for usage of locids, and in turn fixes version-locid resolving by excluding the query-string.
=> Fix ontology state update

.gitignore, lib/tasks/test.rake, spec/controllers/ontology_versions_controller_spec.rb, spec/hets_helper.rb, spec/lib/hets_spec.rb, spec/lib/ontology_batch_parse_worker_spec.rb, spec/lib/tarjan_spec.rb, spec/lib/worker_spec.rb, spec/models/category.rb, spec/models/mapping_spec.rb, spec/models/ontology_spec.rb, spec/models/ontology_version/proving_spec.rb, spec/models/ontology_version_spec.rb, spec/models/repository/git_mv_spec.rb, spec/models/repository/git_spec.rb, spec/models/sentence_spec.rb, spec/models/symbol_mapping_spec.rb, spec/models/symbol_spec.rb, spec/spec_helper.rb
This shall fix #1250.
If no hets server is running, it is started and the fixture files (VCR cassettes) are created. Those fixtures are then used in the specs.
This pull request is based on the branch of #1260 (**1257-introduce_axiom_model**) instead of **staging**. It might be easier to review that one first.
=> 1250 use hets api and vcr for the tests

app/models/ontology_version/parsing.rb, app/models/ontology_version/proving.rb, lib/hets.rb, lib/hets/action_caller.rb, lib/hets/caller.rb, lib/hets/hets_options.rb, lib/hets/prove_caller.rb, lib/hets/prove_options.rb, spec/lib/hets/hets_options_spec.rb, spec/lib/hets/prove_options_spec.rb
This branch introduces `HetsOptions` and `ProveOptions` which allows to easily pass a whole bunch of options to the `ActionCaller`/the Hets API. In #1136, there is already something with this purpose, but it will be replaced by this implementation because this one is tailored to be used with the `ActionCaller` and the Hets API instead of the Hets command line interface.
This pull request is based on the branch of #1261 (**1250-use_hets_api_and_vcr_for_the_tests**) instead of **staging**. It might be easier to review that one first.
=> Introduce hets options

app/models/repository/destroying.rb, lib/collective_proof_attempt.rb, lib/hets/hets_error_process.rb, lib/hets/json_parser.rb, lib/hets/prove/importer.rb, spec/lib/collective_proof_attempt_spec.rb
This shall fix #1280. Hets errors are recognized and the states are updated properly.
This only handles errors in the backend. Views for errors and states are part of #1283.
=> 1280 hets error handling for proving

.travis.yml
Allows gitter to add notifications for travis actions (test-start, -success, -fail) into the gitter chat.
=> Add gitter support for travis

app/controllers/api/v1/base.rb, app/controllers/api_keys_controller.rb, app/controllers/users/api_keys_controller.rb, app/helpers/users/registrations_helper.rb, app/models/api_key.rb, app/models/user.rb, app/views/devise/registrations/edit.html.haml, config/locales/en.yml, config/routes.rb, db/migrate/20150329121431_create_api_keys.rb, features/User.feature, features/step_definitions/user_steps.rb, spec/factories/api_key_factory.rb, spec/models/api_key_spec.rb
Shall close #1292.
Adds API-Keys to the application. Every user can create API-Keys. Only one per user will be valid at any given time. Currently the invalid ones will also be stored indefinitely - we might want to change this later on.
Also adds 'current_user'  handling based on the api-key for the API-Controller. Tests for this part will however have to wait until the first feature is implemented, that actually needs authentication (which will probably be #1156).
=> 1292 add api key

lib/hets/prove/prove_evaluation_helper.rb
This shall fix the "-1 seconds" at "time taken" bug. The `-1` is a value we get from hets so we have no influence on how it is computed. It seems to only occur on instantaneously returning eprover.
=> Fix time taken being negative.

config/application.rb
This shall fix #1264. If the file `#{environment}.local.rb` exists,
it overwrites the configuration defined in `#{environment}.rb`.
=> 1264 load local initializers

script/rebuild-ontohub
Shall close #1328.
Otherwise the result is executed inside of
the bash script, which is problematic if it
contains semicoli for example.
=> quote result of subprocess

app/models/key/fingerprint.rb
This shall fix #1329.
Openssh changed the fingerprint output format in version 6.8. Now it
defaults to SHA256 (previously MD5) and it prepends `MD5:` or `SHA256:`
to the fingerprint.
With `-E md5` we tell it to use the old fingerprint format. This option
is not recognized by versions before 6.8 and calling `ssh-keygen` with
it lets the process fail. To support the older versions as well
(they are running on our productive deployments), we call it a second
time with correct options if we find ourselves in in an environment with
the newer version.
=> Fix ssh key fingerprint generation

app/models/proof_attempt.rb, app/models/tactic_script.rb, app/models/tactic_script_extra_option.rb, app/serializers/proof_attempt_serializer.rb, app/serializers/tactic_script_serializer.rb, db/migrate/20150409051342_create_tactic_scripts.rb, db/migrate/20150409051349_create_tactic_script_extra_options.rb, db/migrate/20150409051440_move_tactic_script_from_proof_attempt_to_separate_model.rb, lib/hets/prove/prove_evaluation_helper.rb, spec/factories/proof_attempt_factory.rb, spec/factories/tactic_script_extra_options_factory.rb, spec/factories/tactic_script_factory.rb, spec/fixtures/vcr/api/json-schemata/ontology/proof_attempt.yml, spec/models/proof_attempt_spec.rb, spec/models/tactic_script_extra_option_spec.rb, spec/models/tactic_script_spec.rb
This gets rid of storing the tactic script as json in the database by introducing a model for it.
~~The branch of this pull request is based on:~~
* ~~1256-add_proving_related_serializers (#1289)~~
~~The first commit of this branch is:~~
~~Add model: TacticScript.	0c2ba71~~
=> Add tactic script model

lib/hets/base_evaluator.rb, lib/hets/concurrent_evaluator.rb
When restructuring the evaluation, I forgot to put the rescue block
cancelling the concurrency handling into the ConcurrentEvaluator.
=> Fix error handling of BaseEvaluator

.gitignore, config/initializers/paths.rb, config/settings.yml, config/settings/development.yml, config/settings/test.yml, doc/productive_deployment.md, git/lib/git_shell.rb, lib/authorized_keys_manager.rb, lib/tasks/git.rake, script/cp_keys.c, script/rebuild-ontohub, spec/controllers/keys_controller_spec.rb, spec/controllers/ssh_access_controller_spec.rb, spec/models/key_spec.rb, spec/spec_helper.rb
This pull request replaces #1197. What it does:
* Make the paths around git configurable.
* Add rake tasks to prepare git authorized_keys handling
* Compile the key-copy binary (and set custom permissions)
* Before compilation, the source file `cp_keys.c` is changed to use the settings which the Rails app uses. Make sure, this rake task is called with the correct RAILS_ENV.
* Create the ontohub-editable authorized_keys with custom permissions file if it doesn't exist
* Print messages on what is yet to do manually (`chown`). We can't do this automatically, because we donÄt know which owner/group we want to set. We could add settings for user/group, but we would to have need root privileges on some systems for `chown`. The root privileges are the reason why I want to let the admin do this …
=> 1170 git handling

app/assets/javascripts/evaluation-state.js.coffee, app/assets/stylesheets/application.css.sass, app/assets/stylesheets/ontology.css.sass, app/assets/stylesheets/state.css.sass, app/controllers/ontologies_controller.rb, app/controllers/proof_attempts_controller.rb, app/fake_records/proof.rb, app/helpers/link_helper.rb, app/helpers/ontology_helper.rb, app/helpers/state_helper.rb, app/models/proof_attempt.rb, app/views/ontologies/_info.html.haml, app/views/ontologies/_status.html.haml, app/views/ontology_versions/_ontology_version.html.haml, app/views/proof_attempts/index.html.haml, app/views/proof_attempts/show.html.haml, app/views/shared/_state.html.haml, app/views/shared/_state_tag.html.haml, app/views/theorems/_theorem.html.haml, app/views/theorems/index.html.haml, config/locales/en.yml, config/routes.rb, features/step_definitions/ontology_state_steps.rb, features/step_definitions/ontology_versions_steps.rb, lib/collective_proof_attempt_worker.rb, spec/controllers/proof_attempts_controller_spec.rb, spec/models/proof_attempt_spec.rb
This shall fix #1284. It also adds retry functionality to failed proof attempts.
~~The branch of this pull request is based on:~~
* ~~add_tactic_script_model (#1311)~~
* ~~1256-add_proving_related_serializers (#1289)~~
~~The first commit of this branch is:~~
~~Move state helper to own module and generalize it.	33f017c~~
=> 1284 show theorem and proof attempt state

lib/tasks/import.rake
The previous code worked flawlessly on a mac, but my ubuntu system could not execute `system` properly. `system` returned `nil` with `$?` being `nil` as well. With the backtick notation it works.
=> Fix logicgraph generation

app/models/prover.rb, app/views/proofs/new.html.haml, config/hets.yml, db/migrate/20150313065037_use_prover_reference_in_proof_attempts.rb, db/migrate/20150320135159_create_proof_attempt_configurations.rb, db/migrate/20150420141258_add_display_name_to_prover.rb, lib/hets/prove/parser.rb, lib/hets/provers/importer.rb, lib/migration_with_data.rb, spec/factories/prover_factory.rb, spec/models/prover_spec.rb
This shall fix #1325 and also use the new `display_name` of Hets' provers list.
Hets now outputs JSON with snake case (instead of camel case) object keys. Our parsers need to be adjusted to this.
--
*Because our CI services use the bleeding-edge version of Hets, they will always fail without the changes of this branch.*
=> 1325 parse hets json snake case keys 

app/models/oops_response.rb
Shall fix #1338.
When introducing `table`, we accidentally replaced the wrong table name
with the `table` variable.
=> Use correct table for JOIN

Rakefile, lib/tasks/test.rake, spec/shared_helper.rb, spec/spec_helper.rb
A simple run of `rspec spec/something_spec.rb:123` spends a lot of time on
generating the coverage report.
This disables the coverage report, except for the default rake task.
If a coverage report is desired even for other tasks, just set the environment variable `COVERAGE`, e.g.:
```
COVERAGE=true rspec
```
=> Report coverage only on default task

app/controllers/files_controller.rb, app/helpers/files_helper.rb, app/helpers/ontology_helper.rb, app/models/ontology.rb, app/models/ontology/associations_and_attributes.rb, app/models/repository/git.rb, app/models/repository/importing.rb, app/views/files/show.html.haml, app/views/ontologies/_info.html.haml, config/locales/en.yml, config/routes.rb, db/migrate/20141008133828_add_has_file_to_ontology.rb, lib/git_repository.rb, lib/git_repository/commit.rb, lib/git_repository/history.rb, lib/repository_update_worker.rb, spec/controllers/files_controller_spec.rb, spec/models/repository/save_and_delete_file_spec.rb, spec/routing/files_routing_spec.rb
This shall fix #617 and #958.
Files in the repository can be deleted now via the web interface. 
Then, their ontologies will be marked as 'not having a file' (`has_file`).
This flag is stored in the database, but only for the head-version of an ontology (as a cache).
One can still ask for a specific commit, if an ontology has a file (`has_file(commit_oid)`), which then accesses the hard drive.
Deletion via ssh is detected and the flag is set in that case.
In the view (ontology#show), the nonexistence of a corresponding file is indicated by text and the absence of a link to the file.
=> 617 handle file deletion

db/seeds/070-oops.rb, lib/tasks/generate.rake, script/rebuild-ontohub, spec/fixtures/seeds/categories.owl, spec/fixtures/seeds/proof_statuses.owl
Seeds depended on an internet connection. With this change they don't:
* Proof statuses and categories have fixtures. They are only used if the download from ontohub.org failed.
* Oops is skipped if either a SocketError (no connection at all) or a RestClient error (e.g. 404 or similar) occurs.
In both cases a message with the error is printed to stdout.
=> Fix run seeds when offline

app/models/repository/git.rb
Shall fix #1282. This is just a small refactoring.
=> Put fallbacks into user_info, use user_info.

spec/lib/repository/history_spec.rb
The history spec had poorly chosen `describe` and `context` descriptions, which are changed here.
Also the nesting of the contexts was bad because there were two `describe` blocks. I changed them into two `context`s inside of one `describe`.
The diff is only this huge because the indentation changed.
=> Refactor history spec

config/database_cleaner.rb
After moving all MiniTests to RSpec, we don't need the config for MiniTest anymore.
=> Remove obsolete database cleaner config

app/assets/javascripts/evaluation-state.js.coffee, app/assets/stylesheets/proof-attempt.css.sass, app/assets/stylesheets/state.css.sass, app/controllers/ontologies_controller.rb, app/helpers/navigation_helper.rb, app/helpers/proof_attempts_helper.rb, app/helpers/state_helper.rb, app/models/proof_attempt_configuration.rb, app/models/tactic_script_extra_option.rb, app/views/ontologies/_info.html.haml, app/views/proof_attempts/_configuration.html.haml, app/views/proof_attempts/_item.html.haml, app/views/proof_attempts/_result.html.haml, app/views/proof_attempts/_sentences_list.html.haml, app/views/proof_attempts/_tactic_script.html.haml, app/views/proof_attempts/index.html.haml, app/views/proof_attempts/show.html.haml, app/views/shared/_state.html.haml, config/locales/en.yml, features/step_definitions/ontology_state_steps.rb, features/step_definitions/ontology_versions_steps.rb
This shall fix #1283. The new proof attempt show page is much cleaner and hides information that is not existent. Also, if a configuration is present, its details are shown.
The branch of this pull request is based on:
* ~~1284-show_theorem_and_proof_attempt_state (#1312)~~
* ~~add_tactic_script_model (#1311)~~
* ~~1256-add_proving_related_serializers (#1289)~~
~~The first commit of this branch is:~~
~~Make state updater box look like a label.	d21a94f~~
=> 1283 improve proving related views

.rspec, .travis.yml, config/cucumber.yml, features/support/env.rb, spec/spec_helper.rb, spec/support/documentation_progress_formatter.rb, spec/support/scenario_progress_formatter.rb
The quite verbose formatter annoyed me a little because it printed way more information than we needed. This pull request adds formatters that combine the strengths of the very verbose formatters `documentation` (for rspec) and `pretty` (for cucumber) and of the too little printing formatter `progress`.
Those are only active by default on development machines. I made sure that the verbose formatters are used on travis and jenkins.
=> Use less verbose test output formatter

doc/developer_installation_on_ubuntu.md
@CarloDib has tried out the ubuntu developer installation and failed. This corrects some problems he encountered.
=> necessary changes to make ubuntu developer installation instructions work

script/rebuild-ontohub
Shall improve the rebuild-ontohub script.
- Execution does not cease if the elasticsearch-wiper gets a 404 response (which basically means that the cache was already wiped)
- Adds the new command to allow such special cases
- Adds the `--no-invoker` switch, which will result in the script doing the following
- no check if invoker is installed
- no start of invoker
- no restart of invoker
=> Fix and allow exceptions for rebuild ontohub

app/helpers/repositories_helper.rb, app/models/ontology_version.rb, app/models/repository/git.rb, app/serializers/action_serializer.rb, app/serializers/application_serializer.rb, app/serializers/formality_level_serializer.rb, app/serializers/license_model_serializer.rb, app/serializers/logic_mapping_serializer.rb, app/serializers/logic_serializer.rb, app/serializers/ontology_type_serializer.rb, app/serializers/repository_serializer.rb, config/initializers/hostname.rb, config/settings.yml, lib/external_repository.rb, lib/hets.rb, lib/iri_url_builder.rb, lib/settings_validation_wrapper.rb, spec/fixtures/vcr/specs/lib/collective_proof_attempt/proof_status_spec/CollectiveProofAttempt_-_SZS_with_SPASS_on_ontology_CounterSatisfiable_after_proving.yml, spec/fixtures/vcr/specs/lib/collective_proof_attempt/proof_status_spec/CollectiveProofAttempt_-_SZS_with_SPASS_on_ontology_Theorem_after_proving.yml, spec/fixtures/vcr/specs/lib/collective_proof_attempt/proof_status_spec/CollectiveProofAttempt_-_SZS_with_eprover_on_ontology_CounterSatisfiable_after_proving.yml, spec/fixtures/vcr/specs/lib/collective_proof_attempt/proof_status_spec/CollectiveProofAttempt_-_SZS_with_eprover_on_ontology_Theorem_after_proving.yml, spec/lib/collective_proof_attempt/proof_status_spec.rb, spec/models/ontology_version_spec.rb, spec/support/common_helper_methods.rb, spec/support/fixtures_generation/pipeline_generator.rb
This automatically reads the hostname from the operating system and uses it in the application if `hostname` is not set in the settings.yml (as @jelmd requested).
=> Use OS hostname if hostname is undefined in settings

.hound.yml, app/controllers/application_controller.rb, app/controllers/ontologies_controller.rb, app/models/ability.rb, app/models/access_token.rb, app/models/ontology_version/parsing.rb, app/models/ontology_version/proving.rb, app/models/repository/access.rb, app/models/repository/associations_and_attributes.rb, app/models/theorem.rb, config/settings.yml, db/migrate/20140820120712_create_access_tokens.rb, lib/access_token_deletion_worker.rb, lib/hets/hets_options.rb, lib/router_constraints.rb, lib/settings_validation_wrapper.rb, spec/lib/access_token_deletion_worker_spec.rb, spec/lib/hets/hets_options_spec.rb, spec/models/ability_spec.rb, spec/models/access_token_spec.rb, spec/models/ontology_version/proving_spec.rb, spec/models/repository/access_spec.rb, spec/models/theorem_spec.rb, test/factories/access_token.rb
This shall fix #558. As soon as hets (https://github.com/spechub/Hets/issues/1422) can handle it completely, this should work. Now, it is working for non-owl files whose file type can be detected by hets' magic.
After merging, don't forget to put this line into the crontab for the expired tokens to be deleted daily:
```
0 0  * * *  ~/current/script/rails runner 'AccessTokenDeletionWorker.new.perform'
```
=> 558 access token for private repositories

db/migrate/20150311125212_make_sentences_to_axioms.rb
This shall fix #1374. I tried to use the garbage collection invoking method, but that's slower than simply restricting the select statement to the one needed column.
The other migrations don't seem to be problematic on the ontohub.org data.
=> 1374 Improve migration performance

db/data/20140823134218_set_basepath_where_nil.rb, db/data/20141102203932_update_display_text_for_obo_sentences.rb, db/data/20150311194246_associate_provers_with_ontology_versions.rb
This shall fix #1376.
Actually, only the first commit (Set basepath where it is nil.	 671a2be) restores consistency. The other ones make sure that the data migrations pass. Since failing data migrations were the main reason of the issue, I put them into this PR as well.
Note:
The data migrations should be run manually with `RAILS_ENV=production nohup rake data:migrate &` to see the IDs of the failing OntologyVersions (see the third commit's message).
--
This way, 138 + 4350 OntologyVersions don't get a list of provers (timeout + other error).
You can find the file containing the logged failing IDs at `develop.ontohub.org:~ontohub/data_migration_provers_failures`
=> 1376 make ontohub org database consistent

app/models/ontology.rb, app/models/ontology/associations_and_attributes.rb, app/models/ontology/class_methods_and_scopes.rb, app/models/ontology/mappings.rb, app/models/ontology/validations.rb, app/models/repository/git.rb, db/migrate/20150607113504_remove_iri_from_ontology.rb, lib/external_repository.rb, lib/hets/dg/node_evaluation_helper.rb, lib/state_updater.rb, spec/factories/ontology_factory.rb, spec/lib/ontology_batch_parse_worker_spec.rb, spec/lib/worker_spec.rb, spec/models/distributed_ontology_spec.rb, spec/models/ontology_spec.rb
During the course of #1351 i've removed the iri-field from ontologies in ontohub. They are superseded by the locid-field. The iri is now only a method to generate the fully-qualified locid.
=> 1351 remove iri field

app/fake_records/proof.rb, spec/lib/proof_spec.rb
This fixes a bug that made the axiom selection a no-op.
=> Fix axiom selection

Gemfile.lock
The current version is not installable on several Linux clients, including travis.
=> Temporarily set libv8 to a previous version

app/models/repository/symlink.rb, config/application.rb, config/initializers/paths.rb, lib/settings_interpreter.rb, lib/settings_validation_wrapper.rb, lib/settings_validation_wrapper/validators.rb, lib/settings_validator.rb
This shall fix #1371. After some settings alterations the output looks something like:
```
❯ RAILS_ENV=production rails c
Rails Error: Unable to access log file. Please ensure that /Users/eugen/Work/Ontohub/ontohub/log/production.log exists and is chmod 0666. The log level has been raised to WARN and the output directed to STDERR until the problem is fixed.
Creating scope :state. Overwriting existing method Repository.state.
Creating scope :accessible_by. Overwriting existing method Repository.accessible_by.
The settings are invalid. Please check your config/settings[.local].yml or config/settings/production[.local].yml
The following errors were detected:
Please check the paths keys in the settings - data_root:
is not a directory
Value: /tmp/abc/data
Please check the paths keys in the …
```
=> 1371 print better readable settings validation errors

.travis.yml, lib/settings_validator.rb
Whenever the settings validations failed, travis and jenkins were green.
However, the settings validations fail because of missing directories. Those are now created in both, travis and jenkins (see also https://github.com/ontohub/ontohub-ci/commit/b7e0d081c62210c8b2712626ee01cc8634650eca).
=> Fix settings validations for the tests

config/application.rb, config/settings.yml, config/settings/development.yml, lib/settings_validation_wrapper.rb
This shall fix #1399.
It is not possible to disable *all* INFO log entries and have settings validations at the same time. The execution order is:
* sidekiq bootup (printing info log entries)
* settings validation
* setting the log level
It is only the bootup log that still has the info level.
=> 1399 allow to configure sidekiq log level

.gitignore, doc/productive_deployment.md, lib/authorized_keys_manager.rb, lib/settings_validation_wrapper.rb, lib/tasks/git.rake
This shall fix #1384 and #1386. It further adds a reasonable default email address to the production.yml.
=> 1384 validate existence of the cp keys binary

config/initializers/devise.rb, config/settings.yml, lib/settings_validation_wrapper.rb, lib/settings_validation_wrapper/validators.rb
Now we can either set `noreply` or `noreply@example.com` as the email
address. If the host-part is omitted, it will be appended automatically.
If the host-part is specified, it must be the same as the FQDN.
=> 1407 Allow to set an email without the host-part

config/initializers/paths.rb, config/settings.yml, config/settings/development.yml, config/settings/test.yml, doc/productive_deployment.md, lib/authorized_keys_manager.rb, lib/settings_validation_wrapper.rb, lib/settings_validator.rb, lib/tasks/git.rake
This shall
* fix #1414
* fix #1415
* print a more useful error message if the cp_keys executable is missing. Previously, this printed a bad key and a bad value (only a good error message itself)
=> Lots of deployment fixes

config/application.rb
The object in the settings is a RailsConfig. Devise needs it to be a Hash, though.
=> 1395 fix problem with e-mail config

config/environments/production.rb
Let's avoid patches and superfluous config files by using better defaults :)
=> Set default log level to warn in production mode.

Rakefile
At the beginning of each run of `rake`, the long `db:migrate:clean` output as well as the list of the spec files annoyed me a little. This change hides that output. The important things, such as the spec progression and the spec report are still shown.
=> Suppress Rspec verbose output

Gemfile, Gemfile.lock, config/application.rb
The previous rails_config version didn't properly overwrite arrays.
This version does overwrite them.
=> Overwrite arrays in config

app/models/key/fingerprint.rb
This should fix
```
Failure/Error: it{ subject.errors[:key].should == ["is not a public key file."] }
expected: ["is not a public key file."]
got: ["is not a public key file.\r"] (using ==)
```
=> Deletes whitespace to fix test.

spec/fixtures/ontologies/dol/reference.dol
The `mapping_spec` depends on ontohub being available. However, with the current server/TLS problems, we need to remove this dependency. Unfortunately, we need an external source (i.e. not on the same ontohub instance that is tested) for the imported fixture file in order for it to be placed in the `ExternalRepository`.
I couldn't find a clean way to do this without depending on a network connection. So instead of depending on Ontohub, we now depend on Github.
=> mapping_spec quick fix

db/migrate/20150625074341_add_axiom_selections.rb
If a ProofAttemptConfiguration had no selected axioms, no AxiomSelection
was created. This violated a not null constraint on axiom_selection_id.
=> Always create AxiomSelections in migration

app/helpers/sentence_helper.rb
This shall fix #1024. It now only displays bold text (removing arrow brackets) for OWL. CASL sentences, for example, still keep their "less than" and "greater than" symbols.
Without this variable being set, the rake task `git:compile_cp_keys` (called by the rebuild script) fails.
=> 1024 sentence display broken

doc/developer_installation_on_mac_os_x_lion_and_up.md, doc/developer_installation_on_ubuntu.md, script/rebuild-ontohub
The GIT_HOME environment variable was not set in the rebuild script.
This adds a default value.
=> Specify GIT_HOME environment variable for rebuild script

config/locales/en.yml, lib/hets/prove/prove_evaluation_helper.rb, lib/proof_evaluation_state_updater.rb, lib/proof_execution.rb, lib/state.rb, lib/state_updater.rb, spec/lib/proof_evaluation_state_updater_spec.rb, spec/lib/proof_status_determining_spec.rb
=> 1443 fix evaluation state on theorems

app/models/basic_proof.rb, db/migrate/20150806044907_remove_basic_proof_model.rb
This should fix #230 by removing the model `BasicProof`. The model was never used and we have other models for proofs.
=> Remove unused BasicProof model.

app/fake_records/proof.rb, config/locales/en.yml
This fixes two little issues:
1. Hets closes the connection after 60 seconds. We shouldn't allow timeouts this long. This is supposed to be reverted as soon as we can have an open connection for as long as the job takes.
2. Since the proving pipeline refactoring the timeout is no longer split across the proof obligations. The hint needed to be adjusted accordingly.
=> Fix proving timeout

Gemfile, Gemfile.lock, app/controllers/filetypes_controller.rb, app/models/hets_instance.rb, config/god/app.rb, config/god/hets_workers.rb, config/settings.yml, db/migrate/20150807083608_add_hets_instance_load_balancing_attributes.rb, db/seeds/001-hets.rb, db/seeds/020-logicgraph.rb, db/seeds/030-proof_statuses.rb, db/seeds/080-metadata.rb, db/seeds/090-categories.rb, lib/hets.rb, lib/hets_instance_force_free_worker.rb, lib/rake_helper.rb, lib/semaphore.rb, lib/settings_validation_wrapper.rb, lib/settings_validation_wrapper/validators.rb, lib/settings_validator.rb, lib/tasks/generate.rake, lib/tasks/hets.rake, lib/tasks/import.rake, spec/factories/hets_instance_factory_factory.rb, spec/hets_helper.rb, spec/lib/hets_instance_foce_free_worker_spec.rb, spec/models/hets_instance_spec.rb, spec/models/ontology_version_spec.rb, spec/spec_helper.rb
This shall fix #1445.
This also adds a new rake task `hets: recreate_hets_instances` to create the `HetsIntance`s from the configuration in the database.
To check if really multiple Hets instances are used, I suggest to prove all theorems of an ontology (e.g. v__T) and prove it with several provers. Then, check the `state_updated_at` attributes of the `HetsInstance`s.
=> 1445 run multiple hets instances

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, config/initializers/rack_profiler.rb
This should introduce the rack-mini-profiler gem in development and production
In Production-Mode only an admin can see the miniprofiler and in development it is for every transaction.
this should help to find the weak points in ontohub to make it faster
=> 1450 ontohub slow

app/fake_records/diff.rb, spec/fake_records/diff_spec.rb
=> 1465 undefined method split for diff too large symbol

lib/semaphore.rb
For example, parsing failed because Sidekiq::Testing was not defined in
both, the production and development environments.
=> Fix Semaphore in synchronous environment

app/views/layouts/application.html.haml
This first part should fix #1477 partially.
It adds a flash message on ontohub.org which leads to test.ontohub.org.
On test.ontohub.org is another flash message, which is in another PR because the two flash messages need to be pushed on different maschines (ontohub.org and test.ontohub.org)
You can find the wiki entry [here](http://wiki.ontohub.org/index.php/How_to_test_Ontohub)
=> Add flash message to announce test ontohub org.

app/views/shared/_ontology_search_response.html.haml, features/OntologySearch.feature, features/step_definitions/ontology_search_steps.rb
We missed something in #1513. The search is broken if there's an ontology with a category.
=> Delete categories from view in search response.

app/models/hets_instance.rb, config/routes.rb
This shall fix #1523. Unfortunately, it is not possible to test Sidekiq's **scheduling**.
It seems to work though:
1. Run the seeds
2. Open the http://localhost:3000/admin/sidekiq/scheduled in one tab and http://ontohub.dev/default/partial_order//v__T//antisymmetric///proof_attempts in another tab
3. Create a ProofAttempt for `antisymmetric`.
4. As soon as the proof is finished, check back at the sidekiq/scheduled tab. There should be no additional scheduled jobs.
=> 1523 hetsinstanceworkers perform too often

lib/tasks/import.rake
It yielded
```
NoMethodError: undefined method `import_logicgraph' for RakeHelper:Module
```
=> Fix rake import:logicgraph.

lib/ontology_batch_parse_worker.rb, lib/timeout_worker.rb, lib/worker.rb
The timeout is only needed to cancel parsing jobs that take longer than
the configured amount of time.
Once the job is done, the TimeoutWorker job can be unscheduled.
This is very similar to #1524 and can't be tested for the same reasons.
This also removes an unused constant.
=> Reduce scheduled timeout workers

lib/hets/prove_caller.rb
The timeout for the prover is not the same as for the HTTP session.
The HTTP session can take much longer than the actual proof because Hets analyses the ontology
again for proving.
=> Fix proving HTTP timeout

spec/models/sine_axiom_selection_spec.rb
This takes care of a leftover of #1522. I seem to have forgotten to remove the `cleanup` specs.
=> Remove spec for removed cleanup method.

lib/hets/prove/prove_evaluation_helper.rb, lib/hets/prove/szs_parser.rb, spec/fixtures/ontologies/prove/prover_output_generator.casl, spec/fixtures/prover_output/ResourceOut/SPASS, spec/fixtures/prover_output/ResourceOut/darwin, spec/fixtures/prover_output/ResourceOut/darwin-non-fd, spec/fixtures/prover_output/ResourceOut/eprover, spec/lib/hets/szs_parser_spec.rb, spec/support/fixtures_generation/prover_output_generator.rb
This shall fix #1542.
It also transforms the status Timeout to ResourceOut for uniformity among the provers.
---
This branch is based on **fix_sine_spec** (#1543) **instead of staging** because the tests are not green otherwise.
=> 1542 detect timeout message of spass

app/views/layouts/application.html.haml, config/locales/en.yml, features/JavaScript.feature, features/step_definitions/javascript_steps.rb, features/support/env.rb
This should fix #864.
It also replaces a deprecated capybara config.
=> 864 show warning if javascript is not activated

lib/hets/hets_error_process.rb
I missed a detail in a review: There were commas in the magic string which don't belong there.
=> Fix error header codes.

lib/worker.rb
This shall fix #1528.
The error was caused by a method that "overwrites" the sidekiq options. I tested it on ontohub.org by async-parsing the ontology versions mentioned in #1528. I am certain that it fixes the issue.
Additionally, I defined the retry-count for failures *that are not caused by concurrently* parsing different ontologies. The concurrency balancing remains unchanged.
=> 1528 find the reason for the empty named queue

lib/ontology_batch_parse_worker.rb, lib/sequential_ontology_batch_parse_worker.rb
This shall fix #1005. It is deployed on develop.ontohub.org. You can test it by executing
```
ontology_version_id = 19426
Sidekiq::Client.push("retry"=>false, "queue"=>"sequential", "class"=>"SequentialOntologyBatchParseWorker", "args"=>[[[ontology_version_id, {"fast_parse"=>true}]]])
```
in the Rails console on develop.ontohub.org and following the log of the sidekiq sequential queue:
```
tail -f ~ontohub/webapp/log/sidekiq-sequential.log
```
There will be an error (UriFetcher::Errors::UnfollowableResponseError: can't follow the response, and response not useable) because of an issue with Hets (#1559). The code, however, is executed and calls Hets which means that it found the class `SequentialOntologyBatchParseWorker`.
=> Extract SequentialOntologyBatchParseWorker into a separate file.

.coffeescript-style.json, .haml-lint.yml, .hound.yml, .javascript-style.json
This adds default and activates config files for the different linters that Hound uses.
The only change to the default configs that I made is to remove the limit of the line length for HAML.
=> Add hound configs

.rubocop.yml, script/stylecheck
This fixes some issues with Hound. There are additional (more fine grained) config keys for rubocop that are configured here.
This is stalled until I fix some more configuration mistakes when going through Hound's comments in the other pull requests.
=> Styleguide fixes

app/controllers/axioms_controller.rb, app/helpers/pagination_helper.rb, app/views/axioms/index.html.haml, app/views/kaminari/_first_page.html.haml, app/views/kaminari/_last_page.html.haml, app/views/kaminari/_next_page.html.haml, app/views/kaminari/_page.html.haml, app/views/kaminari/_paginator.html.haml, app/views/kaminari/_prev_page.html.haml, app/views/ontologies/show.html.haml, app/views/symbols/index.html.haml, app/views/theorems/index.html.haml
This shall fix #1491.
Pagination of objects that have a loc/id must be done with the custom kaminari-option `build_links_from_request: true`. This switches from the default kaminari-generated page-URLs to URLs based on the current request-URL.
=> 1491 error when displaying sentences

app/controllers/ontologies_controller.rb, app/models/ontology.rb, app/models/ontology/import_mappings.rb, app/views/ontologies/_menu.html.haml, config/locales/en.yml, spec/factories/ontology_factory.rb, spec/models/ontology_spec.rb
This shall fix #1251.
--
~~The branch of this pull request is **not based on staging**, but on the one of #1556 (`167-creating_a_new_ontology_version_needs_to_be_propagated`). Revieweing that one first may be easier.~~
~~The first commit of this branch is~~
~~c299dbe Allow to delete an ontology if it is only imported from the same file.~~
=> 1251 fix ontology delete

app/assets/javascripts/repository/edit_remote.js.coffee, app/helpers/repositories_helper.rb, app/models/repository/access.rb, app/models/repository/importing.rb, app/models/repository/validations.rb, app/views/repositories/_form.html.haml, config/locales/en.yml, spec/models/ability_spec.rb, spec/models/repository/access_spec.rb
This shall fix #1084. By splitting the access options into two hashes, we can disable `private_rw` for non-mirrors.
=> 1084 dont allow selection of private readable repository mode

app/models/proof_status/creation_from_ontology.rb, spec/fixtures/seeds/proof_statuses.owl
This solves two issues with the SZS ontology:
* Prefixes had a double `http://`
* Label was ambiguous due becase a wrong prefix was used
=> Fix proof statuses

config/settings_for_development.yml
This allows invoker to start `hets-server` if it is installed instead of `hets`
=> Add hets-server development compatibility.

lib/tasks/elasticsearch.rake
One CPU core was always at 100% because of waiting actively for an interrupt. With this change, the process is simply asleep forever.
=> Sleep instead of waiting actively.

app/models/ontology/associations_and_attributes.rb, app/models/ontology/sentences.rb, app/models/ontology/symbols.rb
This fixes three little issues:
* **During** parsing, `ontology.symbols` was empty, even if there are symbols. This made parsing callbacks that depend on this association fail.
* The method `update_or_create_from_hash` is supposed to return the symbol, but it returned a boolean.
* Code style: Indentation and the place of the association definition were wrong.
I add no test because this only affects the parsing code. I would need to intercept the parsing and then test internals (which is bad style). The effect will be tested implicitly by #1600.
=> Fix symbol parsing and code style

config/processes/app.eye
This shall fix #1602.
It also makes a few more changes to the sidekiq queues:
The number of worker processes is reduced drastically to reduce memory consumption. Each worker process loads the entire application into memory, just like the rails server.
* Instead of having one worker for each hets instance, we now have a single worker for all hets tasks with as many threads as there are hets instances
* The three queues for hets tasks `priority_push`, `hets`, `hets-migrate` are managed by the same sidekiq worker process, but with different prioritizations (see the weights in the code).
* The `hets_load_balancing` queue is now managed by the same worker process as the default queue. We don't need special treatment for load balancing.
This is deployed on develop.ontohub.org.
=> 1602 add a sidekiq queue for migrations

app/models/ontology_version/parsing.rb
This shall fix #1593 in a quick and dirty way to prevent HTTP 5xx errors on ontohub.org.
This is going to be reverted as soon as a proper fix is implemented (which is very complicated).
=> Quick fix #1593.

app/models/ontology_version/parsing.rb, app/models/ontology_version/states.rb, spec/hets_helper.rb, spec/models/ontology_spec.rb
This shall fix #1591.
Most of the changed lines are just fixing test behaviour. Before, we did not just stub the Hets-API call, but the whole parsing process. The last commit fixes this issue by only stubbing Hets and still running the whole rest of the parsing pipeline.
=> 1591 child ontologies are indefinitely pending

app/assets/javascripts/codemirror-custom.js.coffee, app/controllers/path_helpers.rb, app/helpers/ontology_version_helper.rb, app/models/ontology_version.rb, app/views/ontology_versions/_ontology_version.html.haml, app/views/ontology_versions/index.html.haml, features/OntologyVersions.feature, features/step_definitions/ontology_versions_steps.rb
This fixes #1633. Adds edit and show buttons to ontology versions depending on the following factors:
- failed latest version when having write access: edit button
- else: view button to file version at that point
=> 1633 add edit and show buttons to ontology versions

Gemfile, Gemfile.lock, app/models/hets_instance.rb, app/models/ontology_version/parsing.rb, lib/ontology_parsing_worker.rb
This PR closes #1610  and does four things:
- set the `up` flag on `HetsInstance`s correctly when not reachable, so that only online `HetsInstance`s are chosen
- show the correct error message when no `HetsInstance` is available (`There is no HetsInstance which is reachable and has a minimal Hets version of v0.99, 1439380563`)
- schedule a retry job for parsing an ontology for an hour later if no `HetsInstance` is available
- remove already scheduled retries for a specific version when the user hits the `Retry` button, so the same version is only parsed once (unless again there is no `HetsInstance` available, in which case another retry is scheduled)
To achieve the third point I added a new gem `sidekiq-retries` which offers the ability to skip retries or do retries although the max …
=> 1610 offline hetsinstances get chosen and raise errors

Gemfile
Fix error:
```
/local/home/ontohub/ruby/2.2.0/gems/activesupport-3.2.22.2/lib/active_support/dependencies.rb:251:in `require': Please add test-unit gem to your Gemfile: `gem 'test-unit', '~> 3.0'` (cannot load such file -- test/unit/testcase) (LoadError)
```
This occurs when deploying on develop.ontohub.org
=> Fix test-unit load error.

Gemfile, Gemfile.lock, lib/semaphore.rb
This shall fix #1729 and supersede #1730.
With my fork of the redis-semaphore gem, we can simply use the methods of the gem instead of implementing locking on top of it. There, the `locked?` method is fixed.
=> Fix deadlocks caused by semaphore.

lib/ontology_parsing_worker.rb
We need to wait a second for the SQL query to finish. Otherwise there is no OntologyVersion with id=ontology_version_id.
=> wait for sql to finish before parsing worker.

app/models/translated_sentence.rb
This should fix #1655. Note that it still does not work because the model `has_one :locid`, which depends on #1618. So this should probably wait until #1618 is merged.
=> Change has_one to delegate

db/migrate/20160719104019_index_locid_specifics.rb
This significantly speeds up page loading. For example, the landing page took some 1000 ms to load before and now it takes 275 ms. And the file browser view in bioportal took about 94 seconds (!) which slimmed down to 34 seconds.
=> Index specific_* fields in loc_ids table

Gemfile, Gemfile.lock, config/puma.rb
Adds the [puma worker killer](https://github.com/schneems/puma_worker_killer) gem to keep memory usage low.
Should be tested on develop before merging.
=> Add puma_worker_killer gem

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, config/initializers/rack_profiler.rb
This disables profiling because it violates the content policy.
The profiling is active on develop (**only** on develop) with 617ccf03306fd8b9770859474d7a869072d1418f
=> Remove profiler gem

app/assets/javascripts/plugins/graph.js.coffee, app/assets/javascripts/templates/graphs/logic_mappings_edge.hamlbars, app/assets/javascripts/templates/graphs/logic_mappings_node.hamlbars, app/assets/javascripts/templates/graphs/mappings_edge.hamlbars
This shall fix the URL-bug of #1555. It also fixes another URL-bug for the nodes of LogicMappings.
=> 1555 links in details of ontology mapping graphs are wrong

config/settings.yml, lib/settings_validation_wrapper.rb, spec/support/fixtures_generation/base_generator.rb, spec/support/fixtures_generation/direct_hets_generator.rb
This shall fix #1719 by adding a new settings key for the port that Hets shall listen to when generating the test fixtures. We cannot use the `instance_urls` key for this because these instances may all run on other hosts.
=> 1719 test suite does not honor hets port settings

app/controllers/mappings_controller.rb, app/models/mapping.rb, app/views/mappings/index.html.haml
This fixes #1707. It also fixes the related global mappings list (`/mappings`), which also had pagination issues.
=> 1707 pagination in ontology mappings is broken

spec/models/commit_spec.rb
Should (hot)fix #1736. This is clearly not the optimal solution, but as far as I can see the most feasible one.
Can be checked by using an explicit user name like this:
```
let(:pusher) { create :user, name: "Mr. Johnson Jr." }
```
=> "Fix" the pusher/committer test

app/models/ontology/states.rb, app/models/ontology_version/parsing.rb, app/models/repository/git.rb, app/models/repository/importing.rb, config/database_cleaner.rb, db/data/20160310132620_move_loc_id_to_own_model_data.rb, db/seeds/040-git.rb, doc/code_view_on_importing_ontologies.md, lib/hets/dg/node_evaluation_helper.rb, lib/hets/dg/node_evaluator.rb, lib/ontology_parsing_worker.rb, lib/ontology_saver.rb, lib/ontology_version_options.rb, lib/rake_helper.rb, spec/factories/ontology_factory.rb, spec/factories/ontology_version_factory.rb, spec/lib/repository/import/git_spec.rb, spec/lib/repository/import/svn_spec.rb, spec/models/ontology_spec.rb, spec/models/repository/git_mv_spec.rb
This shall fix #1753 and replace #1757.
It removes the `after_create :async_parse` callback from OntologyVersion, because we don't need it. Instead, it schedules a parsing job in the sequential code, when needed.
As a consequence, we do not need the `do_not_parse` flag this much: We have used it to only parse the file once in case of a distributed ontology (and to not parse it for each child ontology). Now, we only use it in the seeds to be explicit and in pushes to call a different ParsingWorker.
=> 1753 wait for sql to finish before parsing worker retry

app/models/ontology/class_methods_and_scopes.rb
This should fix #1749. The returned object was not necessarily an ontology.
=> Check if returned value is an Ontology

config/application.rb, lib/environment_light.rb, lib/environment_light_with_hets.rb
Should fix #1728. `lib` will now be eager loaded. For this to work, we must not load `environment_light` when `Rails` is already defined.
=> 1728 Eager load everything in lib

lib/hets/prove_caller.rb
Remove input type from query string
This is not needed because the input type is already encoded in the json
body of the request. Hets seems to have problems with this parameter, if
it is specified in the query string in a POST request.
=> Hotfix proving

lib/dsl/repo.rb, lib/parsing_callback.rb, lib/parsing_callback/owl.rb, lib/tasks/hets.rake
Because of the eager loading that was introduced in #1780, some classes were loaded multiple times because we have `require` statements in our code. This shall fix it.
Also, Hets could not be started via the rake task that invoker uses because the light environment could not be loaded.
=> Fix requiring libs

lib/repository_pulling_worker.rb
When Sidekiq started, it had 100% CPU load and did not finish loading
the rb files. This is because of a bug is Sidetiq:
https://github.com/tobiassvn/sidetiq/issues/31#issuecomment-23780476
This commit is a workaround for the bug.
=> Fix Sidekiq loading

app/controllers/files_controller.rb, app/controllers/ontologies_controller.rb, app/controllers/proofs_controller.rb, app/helpers/proofs_helper.rb, app/helpers/state_helper.rb, app/views/ontologies/_menu.html.haml, app/views/ontologies/edit.html.haml, app/views/proof_attempts/index.html.haml, app/views/proofs/new.html.haml, app/views/theorems/index.html.haml, config/routes.rb, spec/controllers/ontologies_controller_spec.rb, spec/controllers/proofs_controller_spec.rb
This shall fix only the two cases mentioned in #1458. It gives a glimpse of what needs to be changed to cover everything.
A proper fix could be to implement a better suitable router instead of using Specroutes (which is incompatible to Rails 4.2 anyway).
--
~~This branch is based on `1555-patch_url_for` of #1745 and **not based on staging**. It may be easier to review that one first.~~
=> 1458 loc ids are not used everywhere

git/lib/git_update.rb, lib/ontology_saver.rb
This shall fix #1779. Please test on develop, but be patient because Ontologies are created in the asynchronous jobs (not synchronously as via the web interface). It may take seconds, minutes or even hours for the ontologies to be created. If you look into the Sidekiq web interface, you see that the jobs are created. This is already deployed on develop.ontohub.org.
=> 1779 git push into a repository doesnt start jobs

app/models/repository/validations.rb, lib/git_repository.rb, lib/git_repository/cloning.rb
This shall fix the permission denied error for new repositories: Users should now be able to edit files via both git-push and web.
=> Set group write permissions on repository create
