ontohub/ontohub

- db/migrate/20150209103247_add_omn_to_ontology_file_extensions.rb
> Add migration to evaluate .omn files.

- app/controllers/ontologies_controller.rb
- app/helpers/link_helper.rb
- app/helpers/mappings_helper.rb
- app/models/oops_response.rb
- app/models/repository/git_repositories.rb
- app/views/mappings/index.html.haml
- config/routes.rb
- lib/iri_url_builder.rb
- lib/ontology_version_finder.rb
- lib/router_constraints.rb
This branch/Pull-Request is based on 1154-add_loc-ids/#1179 instead of on staging.
The reason for this is the fact that it needs the previous loc/id work. As soon as the other pull-request
is merged, i will rebase on staging.
This Pull-Request completes the second half and shall therefore close #1154.
> 1154 support ref locids

- .hound.yml
Those two style checks are not according to our style guide. They annoyed me in #1188 and #1208.
> Disable rather annoying style checks.

- app/controllers/logics_controller.rb
- app/models/logic.rb
- app/views/logics/show.xml.haml
- spec/controllers/logics_controller_spec.rb
Should at least be a partial-fix for #1066 and #32. It should be decided by @tillmo whether to merge this and if one or the other (or both) issues should be closed afterwards.
> 1066 provide xml for logics

- app/models/ontology.rb
- app/models/ontology/associations.rb
- app/models/ontology/associations_and_attributes.rb
- app/models/ontology/class_methods_and_scopes.rb
- app/models/ontology/license_models.rb
- app/models/ontology/projects.rb
- app/models/ontology/scopes.rb
- app/models/ontology/searching.rb
- app/models/ontology/states.rb
- app/models/ontology/tasks.rb
- app/models/ontology/tools.rb
- app/models/ontology/validations.rb
- app/models/repository.rb
- app/models/repository/access.rb
- app/models/repository/associations_and_attributes.rb
- app/models/repository/git.rb
- app/models/repository/importing.rb
- app/models/repository/scopes.rb
- app/models/repository/validations.rb
This shall fix #1145 and some other issues that bothered us for a long time.
We had some concerns that were not grouped sensibly. I pushed around some of the code to put a better structure in the concerns of `Repository` and `Ontology`. There is no new code in this branch - just old code moved around a little.
> 1145 regroup concerns

- .gitignore
The settings files in config/environments/ are ruby files and not yml. Those locals need to be ignored.
> Fix ignoring local config files.

- app/controllers/application_controller.rb
- lib/hets.rb
- spec/factories/mapping_factory.rb
- spec/factories/sentence_factory.rb
- spec/factories/symbol_factory.rb
- spec/lib/logicgraph_parser_spec.rb
> safely escape loc/ids in requests/redirects.

- app/controllers/api/v1/children_controller.rb
- app/controllers/api/v1/mappings_controller.rb
- app/controllers/api/v1/ontology_versions_controller.rb
- app/controllers/api/v1/sentences_controller.rb
- app/controllers/api/v1/symbols_controller.rb
- spec/controllers/api/v1/children_controller_spec.rb
- spec/controllers/api/v1/mappings_controller_spec.rb
- spec/controllers/api/v1/ontology_versions_controller_spec.rb
- spec/controllers/api/v1/sentences_controller_spec.rb
- spec/controllers/api/v1/symbols_controller_spec.rb
- spec/fixtures/vcr/api/json-schemata/formality_level.yml
- spec/fixtures/vcr/api/json-schemata/license_model.yml
- spec/fixtures/vcr/api/json-schemata/logic.yml
- spec/fixtures/vcr/api/json-schemata/mapping.yml
- spec/fixtures/vcr/api/json-schemata/ontology.yml
- spec/fixtures/vcr/api/json-schemata/ontology/children.yml
- spec/fixtures/vcr/api/json-schemata/ontology/mappings.yml
- spec/fixtures/vcr/api/json-schemata/ontology/ontology_versions.yml
- spec/fixtures/vcr/api/json-schemata/ontology/sentences.yml
- spec/fixtures/vcr/api/json-schemata/ontology/symbols.yml
- spec/fixtures/vcr/api/json-schemata/ontology_type.yml
- spec/fixtures/vcr/api/json-schemata/ontology_version.yml
- spec/fixtures/vcr/api/json-schemata/repository.yml
- spec/fixtures/vcr/api/json-schemata/sentence.yml
- spec/fixtures/vcr/api/json-schemata/symbol.yml
- spec/support/json_schema_matcher.rb
> 1234 add json for ontology subsites

- app/models/translated_sentence.rb
> Delegate locid to Sentence

- doc/developer_installation_on_ubuntu.md
Removes resque, adds sidekiq to the docs.
> Fix developer installation docs.

- app/assets/stylesheets/application.css.sass
- app/assets/stylesheets/proof.css.sass
- app/helpers/proof_helper.rb
- app/views/proofs/_form.html.haml
- config/locales/en.yml
- lib/collective_proof_attempt.rb
- lib/hets/caller.rb
- lib/hets/prove_caller.rb
- lib/hets/prove_options.rb
- lib/proof.rb
- lib/uri_fetcher/http_caller.rb
- lib/uri_fetcher/post_caller.rb
- spec/factories/theorem_factory.rb
- spec/lib/hets/prove_options_spec.rb
- spec/lib/proof_spec.rb
> 1296 let the user select a proving timeout

- app/assets/javascripts/proofs.js.coffee
- app/assets/stylesheets/proof.css.sass
- app/views/proofs/_form.html.haml
- app/views/proofs/new.html.haml
- config/locales/en.yml
> 1276 improve selection of provers

- Rakefile
- lib/tasks/test.rake
> Abort test execution unless elasticsearch is running.

- config/hets.yml
- lib/hets/prove/parser.rb
- lib/hets/prove/prove_evaluation_helper.rb
- lib/hets/prove/prove_evaluator.rb
- lib/hets/provers/importer.rb
> 1342 adjust to changed hets interface

- doc/productive_deployment.md
This pull request updates the documentation on productive deployment.
The first commit is no more than a style change, fixing a listing by correcting the indentation.
This also shall fix #1244 with the second commit. See its commit message for details.
> Fix productive deployment docs

- app/helpers/state_helper.rb
- app/views/shared/_state.html.haml
- features/OntologyState.feature
- features/step_definitions/ontology_state_steps.rb
- spec/factories/ontology_factory.rb
- spec/factories/ontology_version_factory.rb
- spec/models/repository/retry_failed_spec.rb
> 1349 fix state relations

- spec/controllers/files_controller_spec.rb
- spec/controllers/keys_controller_spec.rb
- spec/controllers/oops_request_controller_spec.rb
> 1364 remove set the flash occurrences

- spec/support/scenario_progress_formatter.rb
> Don't report pending scenarios as failed.

- Gemfile
- doc/most_important_gems.md
- doc/productive_deployment.md
- spec/support/fixtures_generation/base_generator.rb
> Fix: Bundle is not complete for deployment

- Gemfile
- features/support/env.rb
- script/rebuild-ontohub
- spec/spec_helper.rb
- spec/support/fixtures_generation/base_generator.rb
Hotfixes the bundle and includes two non-critical changes to rebuild-script.
> Hotfix bundle

- app/models/hets_instance.rb
- config/settings.yml
- db/seeds/001-hets.rb
- lib/hets_instance_worker.rb
- lib/settings_validation_wrapper.rb
- spec/hets_helper.rb
- spec/models/hets_instance_spec.rb
Shall fix #1373.
Please pay special attention to validation of the new setting, as i am currently not sure if that is the right way to add to the settings validations.
> 1373 update hets instances regularly

- doc/productive_deployment.md
The docs were lacking the path to the config file.
> Fix elasticsearch docs: Mention path to config file.

- app/views/shared/_signin.html.haml
- app/views/shared/_signup.html.haml
- features/step_definitions/user_steps.rb
> Explicitly set IDs on form inputs

- config/initializers/secret_token.rb
- config/settings.yml
- doc/productive_deployment.md
- lib/tasks/secret_replace.rake
> 1398 Add secret_token yml-key to settings

- config/initializers/paths.rb
- lib/settings_validation_wrapper.rb
- lib/settings_validation_wrapper/validators.rb
- lib/settings_validator.rb
This shall fix #1396.
I needed to remove the previous settings validations for the respective keys and add a custom validator class to allow nil values.
--
~~The branch of this pull request is based on **1371-print_better_readable_settings_validation_errors** (#1372)  instead of **staging**. It might be easier to review that one first.~~
~~The first new commit in this branch is~~
~~b2551b5 Add default paths constant to PathsInitializer.~~
> 1396 settings set paths implicitly

- app/models/sentence.rb
- app/views/proof_attempts/index.html.haml
> 1422 hide prove this theorem button if not authorised

- app/controllers/axioms_controller.rb
- app/fake_records/proof.rb
- app/helpers/navigation_helper.rb
- app/models/ontology.rb
- app/models/ontology/categories.rb
- app/models/ontology/sentences.rb
- app/models/sentence.rb
- db/data/20140823134219_set_count_fields_correctly.rb
- db/data/20141102203932_update_display_text_for_obo_sentences.rb
- db/migrate/20150217121518_create_loc_ids_for_existing_ontologies.rb
- db/migrate/20150311125212_make_sentences_to_axioms.rb
- lib/hets/dg/node_evaluator.rb
- lib/hets/prove/prove_evaluation_helper.rb
- lib/hets/prove_options.rb
- lib/tarjan_tree.rb
- spec/lib/axiom_selection_proof_status_spec.rb
- spec/lib/proof_spec.rb
- spec/lib/proof_status_determining_spec.rb
- spec/models/ontology_spec.rb
- spec/models/sentence_spec.rb
This shall fix #1412.
I hope I didn't miss an association call.
> 1412 remove default scope on sentence

- Gemfile
- db/seeds.rb
This shall fix #1448. I checked it on td by running the seeds and there it seems to work (aside from Hets being too old).
> 1448 redesign seeds to be able to use it in production environment

- config/locales/en.yml
> Clarify read/write permissions for repositories.

- config/god/app.rb
> Only start hets for local URLs.

- app/models/ontology.rb
- app/models/ontology/hets_options.rb
- app/models/ontology_version/parsing.rb
- app/models/theorem.rb
- config/hets.yml
- db/migrate/20150805075102_add_file_extension_p.rb
- lib/hets/prove/prove_evaluation_helper.rb
- lib/hets/prove_caller.rb
- lib/hets/prove_options.rb
- lib/tasks/test.rake
- spec/fixtures/ontologies/tptp/Simple_Implications_Group.tptp
- spec/models/ontology_spec.rb
- spec/support/fixtures_generation/direct_hets_generator.rb
- spec/support/fixtures_generation/provers_generator.rb
> 1438 add support for tptp evaluation

- app/models/ontology/sentences.rb
- app/models/theorem.rb
- app/views/proof_attempts/index.html.haml
- app/views/theorems/index.html.haml
- config/hets.yml
- config/locales/en.yml
- db/migrate/20150805104332_add_provable_to_theorems.rb
- spec/factories/theorem_factory.rb
- spec/fixtures/ontologies/tptp/zfmisc_1__t92_zfmisc_1.p
- spec/models/ontology_spec.rb
Shall fix #1439.
--
The branch of this pull request is **not based on staging**. Instead, it is based on the branch of #1440 (1438-add_support_for_tptp_evaluation). It might be easier to review that one first.
> 1439 parse the status attribute of theorems

- lib/semaphore.rb
> Fix Semaphore creating a deadlock in synchronous environment.

- lib/hets/hets_error_process.rb
> added 500 to list of Hets error codes

- config/routes.rb
- public/robots.txt
> 1490 files in public are not accessible

- app/models/hets_instance.rb
- spec/models/hets_instance_spec.rb
> 1502 hetsinstance state stays busy after error

- app/models/proof_attempt.rb
- app/models/sine_axiom_selection.rb
- db/migrate/20151022144003_add_index_on_sine_commonness.rb
- spec/models/sine_axiom_selection_spec.rb
> 1507 improve performance of sine

- app/helpers/navigation_helper.rb
- app/views/ontologies/edit.html.haml
- app/views/shared/_navbar.html.haml
- config/routes.rb
> 1497 remove categories for now

- config/god/app.rb
- lib/hets_instance_force_free_worker.rb
Shall fix #1517. I tested it on te and there it seems to work.
> Add and use queue "hets_load_balancing"

- app/models/hets_instance.rb
- spec/models/hets_instance_spec.rb
> 1525 re check up states of hetsinstances if all are down

- app/models/sine_axiom_selection.rb
Shall fix #1520.
The cleanup is only useful in case of an ungraceful shutdown during the selection. This is the proper use case of a transaction.
I put the whole selection into a transaction to make sure that the finished flag is `true` if and only if the auxiliary objects are available. Thus, the next SineAxiomSelection on the same ontology can reuse them.
> Perform SInE preprocessing in a transaction

- app/fake_records/proof.rb
- app/models/generated_axiom.rb
- app/models/proof_attempt.rb
- app/models/proof_attempt_configuration.rb
- app/models/proof_status.rb
- app/models/sentence.rb
- app/models/sine_symbol_axiom_trigger.rb
- app/models/structured_proof.rb
- app/models/structured_proof_part.rb
- app/models/tactic_script.rb
- app/models/used_sentence.rb
- db/migrate/20151024151554_remove_structured_proofs.rb
- lib/hets/hets_options.rb
- spec/factories/axiom_selection_factory.rb
- spec/factories/tactic_script_factory.rb
- spec/lib/proof_execution_worker_spec.rb
- spec/lib/proof_spec.rb
- spec/models/proof_attempt_configuration_spec.rb
- spec/models/sine_axiom_selection_spec.rb
- spec/models/tactic_script_spec.rb
This shall add missing tests and remove unused methods around proving.
Also, there are some minor refactorings (`alias_attribute`).
> Improve proving test coverage

- doc/backup_and_restore_of_ontohub_data.md
- script/backup
Shall fix #635. Tested successfully on develop. Sudo access is required.
> 635 backup script

- app/models/axiom.rb
- app/models/axiom_selection.rb
- app/models/ontology_member/symbol.rb
- app/models/proof_attempt.rb
- app/models/sine_axiom_selection.rb
> Add missing dependent: :destroy.

- doc/backup_and_restore_of_ontohub_data.md
This adds some more documentation of the backup script. Shall fix #635
> 635 backup

- lib/uri_fetcher/errors.rb
- lib/uri_fetcher/http_caller.rb
- spec/models/hets_instance_spec.rb
> 1579 HetsInstance can't set up state to false

- app/helpers/pagination_helper.rb
This shall fix #1586.
I messed up the code when applying the proper code style. This fixes the issues
* NoMethodError [] for nil
* Wrong number of arguments (3 for 2) for replace_page_params
> 1586 ontologies not displayed

- app/controllers/symbols_controller.rb
- lib/tarjan_tree.rb
- spec/fixtures/ontologies/owl/cycle_with_class_without_inheritance.owl
- spec/lib/tarjan_spec.rb
> 1184 wrong class hierachy tree is displayed

- app/views/devise/passwords/edit.html.haml
> Fix change password title

- app/models/ontology_version.rb
- app/models/proof_attempt_configuration.rb
- app/models/prover_output.rb
- app/models/sentence.rb
- app/models/translated_sentence.rb
> Change delegates to associations.

- lib/ontology_parsing_worker.rb
- lib/worker.rb
> Disable parsing retries.

- app/controllers/home_controller.rb
- app/controllers/ontologies_controller.rb
- app/controllers/ontology_search_controller.rb
- app/models/ontology.rb
- app/models/ontology/class_methods_and_scopes.rb
- app/models/ontology_version.rb
- app/models/repository/scopes.rb
- app/views/shared/_cover.html.haml
- features/OntologySearch.feature
- features/step_definitions/ontology_search_steps.rb
- lib/access_scopes_for_repository_associations.rb
- lib/ontology_search.rb
- spec/factories/repository_factory.rb
- spec/models/ontology_spec.rb
- spec/models/ontology_version_spec.rb
This should fix #964 and fix #1640.
> 964 search results should respect authorization

- app/assets/stylesheets/error-message.css.sass
> Set max error height to 75% of the display height

- app/models/proof_status.rb
- app/serializers/proof_status_serializer.rb
- config/initializers/hostname.rb
- config/routes.rb
- db/migrate/20160110133823_change_proof_status_from_loc_id_to_slug_routing.rb
- lib/slug.rb
- spec/controllers/api/v1/proof_statuses_controller_spec.rb
> 1509 switch proofstatus from loc id to slug

- app/helpers/navigation_helper.rb
> Content tab is not active

- config/processes/app.eye
Shall fix #1537. 
Edit: And it shall fix #1645.
> Remove puma from eye config.

- app/models/team_user.rb
> 1626 Remove duplicate method definition

- .travis.yml
> Change ruby version for travis to 2.2.5

- app/controllers/admin/users_controller.rb
- app/views/admin/users/_form.html.haml
- app/views/admin/users/index.html.haml
- features/Admin.feature
- features/step_definitions/admin_steps.rb
This should fix #1185 and also adds a test for it.
> Cannot edit user

- app/models/team.rb
- db/seeds/010-users_and_teams.rb
> Remove redundant code in team.rb.

- app/models/repository.rb
- app/models/repository/access.rb
- app/models/repository/symlinks.rb
- db/data/20160426082023_recreate_symlinks.rb
- spec/models/repository/symlinks_spec.rb
> 1662 cannot clone formerly private repository using git protocol

- app/assets/javascripts/plugins/relationList.js.coffee
> Dont compare types on value

- app/assets/javascripts/jobs-iframe.js.coffee
- app/views/admin/jobs/index.html.haml
- config/initializers/security_headers.rb
This fixes #1632. At the moment the ~~CSS~~ Javascript seems to be broken, though (the iframe is too small).
> Set X-Frame-Options to SAMEORIGIN

- script/backup
> Fix backup archive creation.

- app/models/loc_id_base_model.rb
- db/data/20160719133546_preload_locids.rb
- lib/graph_structures/specific_fetchers/mappings.rb
Fixes #1765. Same as #1739 apart from the default scope.
> 1765 loc id base model associations are not complete

- app/models/ontology/associations_and_attributes.rb
- app/models/ontology/class_methods_and_scopes.rb
- app/models/ontology/distributed.rb
- app/models/ontology_version/parsing.rb
- app/views/files/_show_dir.html.haml
- app/views/files/_show_file.html.haml
- features/RepositoryEditFile.feature
- features/RepositoryFileBrowser.feature
- features/step_definitions/ontology_search_steps.rb
- features/step_definitions/ontology_state_steps.rb
- features/step_definitions/ontology_versions_steps.rb
- features/step_definitions/repository_edit_file_steps.rb
- features/step_definitions/repository_file_browser_steps.rb
- features/support/env.rb
- lib/hets/dg/node_evaluation_helper.rb
- lib/hets/dg/node_evaluator.rb
- spec/factories/ontology_factory.rb
- spec/fixtures/ontologies/casl/test2_child_deleted.casl
- spec/fixtures/ontologies/casl/test2_child_renamed.casl
- spec/models/ontology_spec.rb
- spec/support/common_helper_methods.rb
This shall fix #1620.
--
~~This branch is based on `1555-patch_url_for` of #1745 and **not based on staging**. It may be easier to review that one first.~~
> 1620 deletion of child ontologies

- app/models/repository/git.rb
This shall fix the mass assignment error.
> Fix mass-assignment error.

- lib/tasks/ontology.rake
This shall fix the rake task `ontology:reanalyze_all`. Sometimes files have been deleted and the ontology is still there. Then, the ontology must be "removed".
> Handle error for ontologies that don't have a file any more.

- lib/hets/hets_error_process.rb
This shall make ontohub more flexible in terms of Hets's error responses.
> Hotfix Hets error handling.

- .travis.yml
Fixes #1781 for now. Intended to be reverted once travis updates to a version that works out of the box.
> Fix bundler shim for travis
